### ISSUE TITLE
TO-DO for first alpha

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/GoZen_GDExtension#1]
### GoZen GDExtension version

-

### Godot version

-

### System information

-

### Issue description

With the GDExtension part finished it's time to make an actual usable video editor! For this I decided to first work on the lite version as this could be my minimum viable project, this way I can more easily experiment with how I will add certain features such as the effects and timeline.

## TO-DO list
_This list is temporary and may change at any moment!_

- [ ] Figure out feature list;
- [ ] UI positioning plan;
- [ ] Data saving system (project + settings);
- [ ] Media pool;
- [ ] Timeline;
- [ ] Project view;
- [ ] Effects panel;
- [ ] Basic effects;
- [ ] Rendering menu;
- [ ] Title support;
- [ ] Color support (color frames);
- [ ] Transitions;

## Feature list
- Basic effects:
  - Transform controls;
  - Volume control;
  - Adjustable timings for animations;
- On screen title support;
- ~~Subtitle support;~~
- Basic transitions;
- ~~Move-able UI;~~
